# Generated by Django 5.1.1 on 2024-10-02 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_alter_student_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='teacher',
            new_name='teachers',
        ),
    ]
